os: linux
sudo: false

language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

branches:
  only:
  - development

install:
 - pip install codecov pytest pytest-cov

script:
 - pytest --cov=training_tracker

after_success:
  - codecov
